### ISSUE TITLE
Gå med i fullstack 2020

### ISSUE THREAD

**Issue by Talica2005** [bjornwann/fullstack-2020-resources#20]
Jag har skapat en mapp "Lektioner screenshot HTML CSS"i min GitHub. Hur kan jag gå med i fullstack 2020 resources?

**Comment by SkySails** [comment]
Följ instruktionerna i readme-filen som finns i detta repos huvudmapp! Det du behöver göra är att skapa en egen gren, i vilken du sedan laddar upp din mapp där du anser att den passar. Därefter pushar du ändringarna och gör en pull request!
Hoppas det besvarar din fråga, om inte så är du välkommen att fråga vidare!
