### ISSUE TITLE
Lägg till W3docs.com bland verktyg och resurser

### ISSUE THREAD

**Issue by Braggedtooth** [bjornwann/fullstack-2020-resources#23]
https://www.w3docs.com/

**Comment by SkySails** [comment]
@Braggedtooth , var tanken att enbart lägga in en referens till W3 som helhet eller var tanken att länka till specifika artiklar?

**Comment by Braggedtooth** [comment]
I sin helhet, finns jätte bra how tos där om html css java osv

**Comment by SkySails** [comment]
Så sant, så sant! Det gör det verkligen. Om man skall tolka din påfyllning av "Assignees"-listan i enlighet med vad [GitHub fastställt](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users) så arbetar 9 enskilda personer på detta just nu? 😅

**Comment by Braggedtooth** [comment]
HAHAH my bad, läste fel...
